apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website
  annotations:
    nginx.ingress.kubernetes.io/app-root: /blog
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - http:
      paths:
      - path: /blog
        backend:
          serviceName: website
          servicePort: 80