baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5
RelativeURLs=true
CanonifyURLs=true

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Container Workflows"
    subtitle = "Test!"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Container Workflows"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "showcase"
